// type enumerations
export const SHOW_MESSAGE = 'SET_MESSAGE'
export const FOUND_DEVICE = 'FOUND_DEVICE'
export const CURRENT_DEVICE = 'CURRENT_DEVICE'
export const MODULE_INIT = 'MODULES_INIT'
export const PROGRAMS_INIT = 'PROGRAMS_INIT'
export const CONTROLS_INIT = 'CONTROLS_INIT'
export const PROGRAM = 'PROGRAM'
export const CONTROL = 'CONTROL'
//export const INIT_COMPLETE = 'INIT_COMPLETE'
//export const EFFECT_PROP = 'EFFECT_PROP'
//export const SYNTH_PROP = 'SYNTH_PROP'
